#!/bin/bash     -       Added for Syntax Highlighting!

#Bash Aliases

alias sx='startx'

alias sudo='sudo '
alias vim='nvim'
alias r='ranger'

alias rm='rm -i'
alias mv='rm -i'
alias cp='cp -i'

alias ls='ls --color=auto --group-directories-first'
alias l='ls -lh'
alias ll='ls -l'
alias lll='ls -lhAF'
alias llll='ls -lAF'

alias grep='grep --color=auto'
