#!/bin/bash             -       Added for Syntax Highlighting!

# Building the Bash Prompt

function prompt_command() {
    local EXIT="$?"
    
################ COLORS ###############

    local black="\[\e[0;30m\]"
    local red="\[\e[0;31m\]"
    local green="\[\e[0;32m\]"
    local yellow="\[\e[0;33m\]"
    local blue="\[\e[0;34m\]"
    local magenta="\[\e[0;35m\]"
    local cyan="\[\e[0;36m\]"
    local lightGray="\[\e[0;37m\]"
    local darkGray="\[\e[0;90m\]"
    local lightRed="\[\e[0;91m\]"
    local lightGreen="\[\e[0;92m\]"
    local lightYellow="\[\e[0;93m\]"
    local lightBlue="\[\e[0;94m\]"
    local lightMagenta="\[\e[0;95m\]"
    local lightCyan="\[\e[0;96m\]"
    local white="\[\e[0;97m\]"

    local lightGrayEx="\[\x1b[38;2;220;220;220m\]"
    local lightBlueEx="\[\x1b[38;2;102;217;239m\]"
    local lightMagentaEx="\[\x1b[38;2;249;38;114m\]"
    local lightPurpleEx="\[\x1b[38;2;174;129;255m\]"
    local lightGreenEx="\[\x1b[38;2;166;226;46m\]"
    local lightYellowEx="\[\e[38;2;255;240;90m\]"
    local lightYellowLimeEx="\[\x1b[38;2;200;216;64m\]"
    local lightPurpleSatEx="\[\x1b[38;2;132;83;200m\]"
    local lightLimeEx="\[\x1b[38;2;144;255;26m\]"
    local lightMagentaDesatEx="\[\x1b[38;2;185;63;102m\]"

############### SPECIAL CHARACTERS #############
    
    local resetColor="\[\e[0m\]"
    local resetEx="\[\x1b[0m\]"

    local bold="\[\x1b[1m\]"
    local italic="\[\x1b[3m\]"
    local underline="\[\x1b[4m\]"

    local dot="$(printf ${lightYellowLimeEx}'\xE2\x80\xA2'${lightGray})"
    local arrow="$(printf ${lightYellowLimeEx}'\xEF\x83\x9A'${lightGray})"
    local doubleArrow="$(printf ${lightYellowLimeEx}'\xc2\xbb'${lightGray})"
    local promptEnd="$(printf ${lightYellowLimeEx}'\xEF\x81\x94'${resetEx})"

############## PROMPT PARTS ################

    local at="$(printf ${lightPurpleEx}@${lightGray})"
    local hostname="$(printf ${lightMagentaEx}${HOSTNAME}${lightGray})"
    local dir="$(printf ${lightGray}[${lightGreenEx}"$(dirs)"${lightGray}])"
    local error=""


    if [ "${UID}" -eq 0 ]; then
        local user="$(printf ${bold}${lightRedD}${USER}${lightGray})"
    else
        local user="$(printf ${bold}${lightBlueEx}${USER}${lightGray})"
    fi
       

    if [ $EXIT != 0 ]; then
        local error="${lightGray}[${red}${EXIT}${lightGray}] "
    fi

            
    if [ -f /usr/share/git/completion/git-prompt.sh ]; then                     # Enable __git_ps1
        . /usr/share/git/completion/git-prompt.sh
    fi
    local gitBranchColored="${lightCyan}$(__git_ps1)${lightGray}"

    #PS1="${error} ${dot} ${user}${at}${hostname} ${doubleArrow} ${dir} ${gitBranchColored}\n> "
    #PS1="${error} ${dot} ${user}${at}${hostname} ${doubleArrow} ${dir}$(__git_ps1)\n> "
    PS1="${dot} ${error}${user}${at}${hostname} ${arrow}${dir}${gitBranchColored}\n${promptEnd} "
}
